global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.wittymeadow-ceeb0d9e.brazilsouth.azurecontainerapps.io:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki.wittymeadow-ceeb0d9e.brazilsouth.azurecontainerapps.io:3100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana.wittymeadow-ceeb0d9e.brazilsouth.azurecontainerapps.io:3000']
  
  - job_name: 'users-api'
    static_configs:
      - targets: ['users-api:5001']

  - job_name: 'games-api'
    static_configs:
      - targets: ['games-api:5001']
