name: Build/Push Grafana Image Only

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/grafana-image-only.yml

jobs:
  build-push-grafana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create/Update Azure Container App 'grafana'
        run: |
          if az containerapp show --name grafana --resource-group Fase-3 &> /dev/null; then
            echo "Atualizando o container app 'grafana'..."
            az containerapp update \
              --name grafana \
              --resource-group Fase-3 \
              --image grafana/grafana:latest \
              --cpu 0.5 \
              --memory 1Gi
          else
            echo "Criando o container app 'grafana'..."
            az containerapp create \
              --name grafana \
              --resource-group Fase-3 \
              --environment managedEnvironment-Fase-3 \
              --image grafana/grafana:latest \
              --ingress external \
              --target-port 3000 \
              --cpu 0.5 \
              --memory 1Gi
          fi
        shell: bash