name: Build/Push Loki Image Only

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/loki-image-only.yml

jobs:
  build-push-loki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create/Update Azure Container App 'loki'
        run: |
          if az containerapp show --name loki --resource-group Fase-3 &> /dev/null; then
            echo "Atualizando o container app 'loki'..."
            az containerapp update \
              --name loki \
              --resource-group Fase-3 \
              --image grafana/loki:latest \
              --cpu 0.5 \
              --memory 1Gi
          else
            echo "Criando o container app 'loki'..."
            az containerapp create \
              --name loki \
              --resource-group Fase-3 \
              --environment managedEnvironment-Fase-3 \
              --image grafana/loki:latest \
              --ingress external \
              --target-port 3100 \
              --cpu 0.5 \
              --memory 1Gi
          fi
        shell: bash