name: Build/Push Prometheus Image Only

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/prometheus-image-only.yml

jobs:
  build-push-prometheus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Prometheus custom image
        run: |
          docker build -f Dockerfile -t 997353105/prometheus-fcg:custom .
          echo "Imagem Prometheus customizada buildada."

      - name: Login no Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Prometheus custom image
        run: docker push 997353105/prometheus-fcg:custom
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create/Update Azure Container App 'prometheus'
        run: |
          if az containerapp show --name prometheus --resource-group Fase-3 &> /dev/null; then
            echo "Atualizando o container app 'prometheus'..."
            az containerapp update \
              --name prometheus \
              --resource-group Fase-3 \
              --image 997353105/prometheus-fcg:custom \
              --cpu 0.5 \
              --memory 1Gi
          else
            echo "Criando o container app 'prometheus'..."
            az containerapp create \
              --name prometheus \
              --resource-group Fase-3 \
              --environment managedEnvironment-Fase-3 \
              --image 997353105/prometheus-fcg:custom \
              --ingress external \
              --target-port 9090 \
              --cpu 0.5 \
              --memory 1Gi
          fi
        shell: bash